spring:
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true

---

spring:
  config:
    activate:
      on-profile: local
      
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/dev
    username: root
    password: 1662
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
     properties:
      hibernate:
       ddl-auto: update
       dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    prefix: classpath:/templates/  
    suffix: .html 

---


#spring:
#  config:
#    activate:
#      on-profile: dev
#
#  datasource:
#    url: jdbc:mysql://core.crugw6444lao.ap-northeast-2.rds.amazonaws.com:3306/core?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: core
#    password: core1q2w3e4r
#
#  jpa:
#    hibernate:
#      ddl-auto: none

---

#spring:
#  config:
#    activate:
#      on-profile: test
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/pjt?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password:
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect